name: lafedejesus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chewie_audio:
  video_player:
  flutter_spinkit:
  sleek_circular_slider:
  flutter_swiper: ^1.1.6
  cupertino_icons: ^0.1.2
  gradient_widgets: ^0.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/db.json
    - assets/imagenes/

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito.ttf

      - family: GochiHand
        fonts:
          - asset: assets/fonts/GochiHand-Regular.ttf
      
      - family: SHOWG
        fonts:
          - asset: assets/fonts/SHOWG.TTF
      
      - family: Acme
        fonts:
          - asset: assets/fonts/Acme-Regular.ttf

      - family: Caveat
        fonts:
          - asset: assets/fonts/Caveat-Regular.ttf
