name: lafedejesus
description: Cursos_biblicos_v2

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Iconos
  cupertino_icons: ^0.1.2
  
  #Estilo de texto
  gradient_widgets: ^0.5.0

  #Pluging Audio
  chewie_audio:
  
  #Plugin Video
  video_player:
  
  #Loading
  flutter_spinkit:
  
  #Programacion - Bloc
  flutter_bloc: ^4.0.0
  equatable: ^1.0.0
  meta: ^1.1.6
  shared_preferences: ^0.5.5

  #Plugin para el icono de la app
  flutter_launcher_icons: ^0.7.4



dev_dependencies:
  http: 
  flutter_test:
    sdk: flutter

#Icono de la app
flutter_icons:
  image_path: "assets/imagenes/icono-app.png"
  android: true 
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/db.json
    - assets/imagenes/

  fonts:

      - family: GochiHand
        fonts:
          - asset: assets/fonts/GochiHand-Regular.ttf
      
      - family: SHOWG
        fonts:
          - asset: assets/fonts/SHOWG.TTF
      
      - family: Acme
        fonts:
          - asset: assets/fonts/Acme-Regular.ttf
