name: lafedejesus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sleek_circular_slider:
  flutter_swiper: ^1.1.6
  video_player:
  chewie_audio:
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/db.json

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf

      - family: GochiHand
        fonts:
          - asset: assets/GochiHand-Regular.ttf
      
      - family: SHOWG
        fonts:
          - asset: assets/SHOWG.TTF
      
      - family: Acme
        fonts:
          - asset: assets/Acme-Regular.ttf

      - family: Caveat
        fonts:
          - asset: assets/Caveat-Regular.ttf
